version: 2
jobs:
  build:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: testim/docker-cli
    steps :
      - run: mkdir -p $CIRCLE_TEST_REPORTS/testim/
      - run: testim  --token "HFPMMWmDBgphmMFNcfS4oxVts7JPyZChVl1rYgGXBPs5pkKT8C"  --project "8iuIg6jOYNgj5YnNs5RJ" --suite "Multiple Error Test Suite" --grid "Testim-Grid" --report-file $CIRCLE_TEST_REPORTS/testim/results.xml
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_test_results:
          path: /tmp/circleci-test-results