version: 2
jobs:
  build:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: testim/docker-cli
    steps:
      - run: mkdir -p $CIRCLE_TEST_REPORTS/testim/
      - run: testim --token "gYbQ7tPXM9MRHmrs5KMDMkSrPA2wGE7ESqIRmlrqRSm1gcDUOM" --project "FhXRJZiD4rHFyvvvYvxB" --grid "Testim-Grid" --report-file $CIRCLE_TEST_REPORTS/testim/results.xml
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_test_results:
          path: /tmp/circleci-test-results